# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


variables:
  azureSubscriptionEndpoint: 'ubearcat-rm-svc'
  azureContainerRegistry: 'ubearcat'
  azureResourceGroup: 'Test'
  kubernetesCluster: 'ubearcat'
  AIRFLOW_NAME: 'airflow-cluster'
  AIRFLOW_NAMESPACE: 'test'
steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure subscription 1(c1c4a4ac-b4b5-44af-bb2a-d3eddc669f67)'
    KeyVaultName: 'ubearcatVault'
    SecretsFilter: '*'
    RunAsPreJob: false
    
- task: HelmDeploy@0
  displayName: Helm deploy
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: repo
    arguments: add airflow-stable https://airflow-helm.github.io/charts
- task: HelmDeploy@0
  displayName: Helm Add Repo
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: repo
    arguments: update

- task: HelmDeploy@0
  displayName: Helm install 
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: install
    chartName: airflow-stable/airflow
    valueFile: custom-values.yml
    arguments: --namespace $(AIRFLOW_NAMESPACE) --version "8.X.X" 
